# Site Info
title: RainDropInTheOcean
tagline: 'A Jekyll theme based on Lanyon'
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'
baseurl: "/greenlight"
url: https://jasmineottawa.github.io
logo: '/public/logo.gif'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Jasmine
  description: An Oracle DBA, Dive into Open Source ocean.
  gravatar: ...... # md5 hash of your email address
  contact:
    linkedin:  
    github:    
    # facebook:  <hide>
    twitter:   
    weibo:     
    email:    

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'https://jasmineottawa.github.io'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/rainDrops.PNG
  caption: Green Light

# Plugins
mathjax: false # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: '' # leave blank if you don't want disqus

